#!/usr/bin/env bash

# SPDX-FileCopyrightText: Copyright The Moby Authors
# SPDX-License-Identifier: Apache-2.0

# This script validates that the seccomp profile generation is done correctly.

# We run 'go generate' and see if we have a diff afterwards
go generate ./seccomp/ > /dev/null
# Let see if the working directory is clean
diffs="$(git status --porcelain -- seccomp 2> /dev/null)"
if [ "$diffs" ]; then
	{
		echo 'The result of go generate ./seccomp/ differs'
		echo
		echo "$diffs"
		echo
		echo 'Please re-run go generate ./seccomp/'
		echo
	} >&2
	false
else
	echo 'Congratulations!  Seccomp profile generation is done correctly.'
fi
